- Python/ibmcloudsql/SQLQuery.py
Solves issue #1 with the parens when running with Python 3.6
> Added parens to print statement

- Node/.gitignore
- Node/.npmignore
- Node/README.md
- Node/package.json
- Node/sqlQuery.js
Added the JS code and README for installation. Will add it to the npm repository as well. Would like some guidance on that since it is an IBM package. I know we have the COS npm package published, but I am not entirely sure about any legal issues, or whether we want to create an npm org for our stuff. Any thoughts?
> Added Node

- Node/lib/sqlQuery.js
To separate library from the readme and package.json files.
> Moved sqlQuery.js to lib folder

- README.md
> Adds build badge

- .travis.yml
DRY by using YAML alias
See details from [Build Stages: Defining steps using YAML aliases - Travis CI](https://docs.travis-ci.com/user/build-stages/using-yaml-aliases/)
> Simplify Travis CI build configuration

- Python/Pipfile
- Python/Pipfile.lock
- Python/ibmcloudsql/SQLQuery.py
- Python/tests/test_sqlquery.py
Supports #37
After this change, my following example works:
```Python
import os
import ibmcloudsql
import pandas as pd
API_KEY = os.environ.get('IBMCLOUD_API_KEY')
INSTANCE_CRN = os.environ.get('SQLQUERY_INSTANCE_CRN')
TARGET_COS_URL = 'cos://us-south/xxx/result/'
sqlClient = ibmcloudsql.SQLQuery(API_KEY, INSTANCE_CRN, target_cos_url=TARGET_COS_URL)
sqlClient.logon()
sql = 'SELECT * FROM cos://us-south/xxx/yyy/ WHERE dt = \'2019-06-02\' LIMIT 5'
df = sqlClient.run_sql(sql)
print(df)
```
I would prefer to complete experiment on branch `experiment-requests` then try to merge with validation by an integration test case like :point_up example.
> tornado -> requests

- Python/setup.py
> Keeps setup.py consistent with Pipfile

- Python/ibmcloudsql/SQLQuery.py
This is a follow up of #43 
I tried to reproduce this bug but it's hard to fail robust API requests from an actual service
Which also reminds me the importance of #39 since none of those exception handling part is covered by automated test cases.
> Fixes undefined HTTPError

- Python/ibmcloudsql/SQLQuery.py
- Python/setup.py
Supports https://github.com/IBM-Cloud/sql-query-clients/issues/45
> Fix errors related to the switch to requests from tornado

- Python/ibmcloudsql/SQLQuery.py
- Python/ibmcloudsql/test.py
Changes to get_result method to support JSON output
> Support for JSON output results

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- Python/ibmcloudsql/SQLQuery.py
> Deal with Sql query that does not return "resultset_location"

- Python/ibmcloudsql/SQLQuery.py
This PR fix related issue when 'resultset_location' is not available. Many existing APIs fail if this is not fixed.
> Fix issue #2

- Python/ibmcloudsql/SQLQuery.py
Fixes #61 
In order to include test case for the method `list_cos_objects`, it will use either _Mock_ or [spulec/moto](https://github.com/spulec/moto/). I will try to defer the decision into another PR.
> Fixes error 'variable used before assignment'

- docs/source/intro.rst
Don't understand the following: To install your package from source in this repository in editable mode, run the following:
> Doc review

- docs/source/cos.rst
- docs/source/ibmcloudsql.rst
- docs/source/sql_magic.rst
- docs/source/sql_query.rst
I fix a few title format issues that Andrea accidentally created when revising the title content.
> fix title format

- Python/ibmcloudsql/SQLQuery.py
- Python/ibmcloudsql/__init__.py
- Python/ibmcloudsql/catalog_table.py
- Python/ibmcloudsql/exceptions.py
- Python/ibmcloudsql/sql_magic.py
- Python/ibmcloudsql/test.py
- docs/source/sql_magic.rst
SQLQuery:
* new exception (SqlQueryInvalidPlanException) to handle when users using a feature not available in the current purchase plan, e.g. Lite Plan
* revise get_schema_data: can detect wrong type
SQLMagic:
* add 2 new APIs (join_table_, joint_cos_) to SQLMagic
* fix store_at_() API
* revise reset_() API
HIVEMetastore:
* improve and fix bug in create_table() 
---
update docs 
add new test cases
> Update docs and revise code

- Python/ibmcloudsql/SQLQuery.py
- Python/ibmcloudsql/catalog_table.py
- Python/ibmcloudsql/cos.py
- Python/ibmcloudsql/test.py
fix: update is_valid_cos_url
update test.py
> Fix failing test.py

- Python/ibmcloudsql/SQLQuery.py
- Python/ibmcloudsql/__init__.py
- Python/ibmcloudsql/test.py
* fix bug
* improve detection of malformed SQL statement
> Revise code

- README.md
> Add badges of GitHub actions

- .github/workflows/python-ci.yaml
- Python/Pipfile.lock
- Python/ibmcloudsql/SQLQuery.py
- Python/ibmcloudsql/__init__.py
- Python/ibmcloudsql/utilities.py
- Python/setup.py
NOTE: Admin needs to increase the version number.
> fix bug in analyze() API

- Python/ibmcloudsql/SQLQuery.py
- Python/ibmcloudsql/__init__.py
- Python/ibmcloudsql/exceptions.py
What: not only retry on 502, but also 524 as a timeout may be intermittent, it's not a terminal problem
> Retry on 524 (timeout in cloudflare)

- Python/README.md
as suggested in https://github.ibm.com/SqlServiceWdp/main/issues/5214
> add info related to Pyinstaller

- Python/ibmcloudsql/utilities.py
> Fix(login): Fixes incorrect retry evaluation
